export const LOGIN_ACTION = "LOGIN_ACTION";
export const GET_USER = "GET_USER";
export const LOGOUT_ACTION = "LOGOUT_ACTION";

export const FIND_DEPARTMENT = "FIND_DEPARTMENT";
export const EDIT_DEPARTMENT = "EDIT_DEPARTMENT";
export const SAVE_EDIT_DEPARTMENT = "SAVE_EDIT_DEPARTMENT";

export const FIND_DOCTOR = "FIND_DOCTOR";
export const EDIT_DOCTOR = "EDIT_DOCTOR";
export const SAVE_EDIT_DOCTOR = "SAVE_EDIT_DOCTOR";

export const GENERAL_FIND_DEPARTMENT = "GENERAL_FIND_DEPARTMENT";

export const APPOINTMENT_SELECT_DEPARTMENT = "APPOINTMENT_SELECT_DEPARTMENT";
export const APPOINTMENT_SELECT_DOCTOR = "APPOINTMENT_SELECT_DOCTOR";
export const APPOINTMENT_SET_DOCTORLIST = "APPOINTMENT_SET_DOCTORLIST";
export const APPOINTMENT_SET_APPOINTMENTLIST =
  "APPOINTMENT_SET_APPOINTMENTLIST";

export const NEXT_APPOINTMENT_CAROUSEL = "NEXT_APPOINTMENT_CAROUSEL";
export const PREV_APPOINTMENT_CAROUSEL = "PREV_APPOINTMENT_CAROUSEL";
export const SET_APPOINTMENT_CAROUSEL = "SET_APPOINTMENT_CAROUSEL";
export const APPOINTMENT_CLEAR_REDUCER = "APPOINTMENT_CLEAR_REDUCER";
export const FIND_USER_WITH_APPOINTMENT = "FIND_USER_WITH_APPOINTMENT";
export const FIND_DOCTOR_WITH_APPOINTMENT = "FIND_DOCTOR_WITH_APPOINTMENT";
