export const LOGIN_ACTION = "LOGIN_ACTION";
export const GET_USER = "GET_USER";
export const LOGOUT_ACTION = "LOGOUT_ACTION";

export const FIND_DEPARTMENT = "FIND_DEPARTMENT";
export const EDIT_DEPARTMENT = "EDIT_DEPARTMENT";
export const SAVE_EDIT_DEPARTMENT = "SAVE_EDIT_DEPARTMENT";
